# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11c1cf03c94af0c0365dbd81c777778e5535f1d83bbf587c90abbcd0a38ddfcdb86ea5811648f8395f00d3b11c322e29c2ca64950d2551393300d5dd2e8d7490

test:
  secret_key_base: 34c7f25901a25db8a4a94e40cbd6d35e228fc4daffa37d5bfa8fc2531c08683d879214c64c11035960efd4b50621d60f1cf148f5fe5cd52aa8f1cddd8949628d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
